name: "Deploy Class Commands"

on:
  push: 
    tags:
      - "class-commands/v*"           
env:
  PROJECT_PATH: WPF_ClickOnce/WPF_ClickOnce.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - run: dotnet publish ${{ env.PROJECT_PATH }}

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          pattern: WPF_ClickOnce/Installer/*.exe
          release-url: https://uploads.github.com/repos/karma994/ClickOnceInstaller/releases/${{ steps.create_release.outputs.id }}/assets{?name,label}